import {
  profileData,
  videoProjects,
  designProjects,
  expertiseList,
  academicList,
  academicListBn,
  trainingDataEn,
  trainingDataBn,
} from './data';
import { SiteConfig } from './types';

export const defaultSiteConfig: SiteConfig = {
  theme: {
    accentPreset: 'sky',
    accentColor: '#38bdf8',
    accentSecondary: '#10b981',
    bgTone: '#07080a',
    sectionPadding: 'normal',
    containerWidth: 'wide',
    fontScale: 'normal',
    cardRadius: '2xl',
  },
  visibility: {
    hero: true,
    portfolio: true,
    expertise: true,
    education: true,
    contact: true,
  },
  profile: { ...profileData },
  elementStyles: {},
  hero: {
    badgeTextEn: 'Digital Marketing Specialist',
    badgeTextBn: 'ডিজিটাল মার্কেটিং স্পেশালিস্ট',
    badgeRoleEn: 'Meta Ads & Growth Strategist',
    badgeRoleBn: 'মেটা অ্যাডস ও গ্রোথ স্ট্র্যাটেজিস্ট',
    titleFirst: 'AMIR',
    titleLast: 'HAMZA',
    subtitleEn: 'Results-Driven Digital Marketing, Meta Ads Campaigns & High-ROI Creative Production',
    subtitleBn: 'ফলাফল-কেন্দ্রিক ডিজিটাল মার্কেটিং, মেটা অ্যাডস ক্যাম্পেইন ও হাই-কনভার্সন ক্রিয়েটিভ প্রোডাকশন',
    ctaPrimaryTextEn: 'Explore Campaigns & Works',
    ctaPrimaryTextBn: 'ক্যাম্পেইন ও কাজের নমুনা',
    ctaPrimaryLink: '#portfolio',
    ctaSecondaryTextEn: "Let's Talk",
    ctaSecondaryTextBn: 'কথা বলুন',
    ctaSecondaryLink: '#contact',
  },
  portfolio: {
    badgeEn: 'Campaigns & Portfolio',
    badgeBn: 'ক্যাম্পেইন ও পোর্টফোলিও',
    titleEn: 'Featured',
    titleBn: 'আমার নির্বাচিত',
    highlightWordEn: 'Marketing & Media',
    highlightWordBn: 'ক্যাম্পেইন ও প্রজেক্টসমূহ',
    descEn: 'Targeted commercial ad campaigns, registration promos, viral reels, and high-CTR marketing thumbnails engineered for maximum ROI.',
    descBn: 'টার্গেটেড কমার্শিয়াল অ্যাড ক্যাম্পেইন, রেজিস্ট্রেশন প্রোমো, ভাইরাল রিলস এবং উচ্চ কনভার্সন থাম্বনেইল ডিজাইনের সংকলন।',
    videoProjects: [...videoProjects],
    designProjects: [...designProjects],
  },
  expertise: {
    badgeEn: 'Core Expertise & Skills',
    badgeBn: 'কোর এক্সপার্টিজ অ্যান্ড স্কিলস',
    titleEn: 'Empowering Brands with',
    titleBn: 'যেসব বিষয়ে আমি',
    highlightWordEn: 'Digital Strategy & Media',
    highlightWordBn: 'পারদর্শী ও অভিজ্ঞ',
    descEn: 'Scaling brands through laser-targeted Meta advertising, high-retention video editing, and conversion-optimized graphic design.',
    descBn: 'সুনির্দিষ্ট মেটা বিজ্ঞাপন, হাই-রিটেনশন ভিডিও এডিটিং এবং কনভার্সন-অপটিমাইজড গ্রাফিক ডিজাইনের মাধ্যমে ব্র্যান্ডের বিক্রয় ও প্রবৃদ্ধি নিশ্চিত করি।',
    items: [...expertiseList],
    toolsStack: [
      { name: 'Meta Ads Manager', category: 'Targeting & Growth' },
      { name: 'Meta Business Suite', category: 'Page & Pixel' },
      { name: 'Adobe Premiere Pro', category: 'Video Editing' },
      { name: 'Adobe After Effects', category: 'Motion Typography' },
      { name: 'Adobe Photoshop', category: 'Creative Ads' },
      { name: 'Adobe Illustrator', category: 'Vector & Branding' },
      { name: 'Canva Pro', category: 'Rapid Social Design' },
    ],
  },
  education: {
    badgeEn: 'Education & Career',
    badgeBn: 'শিক্ষা ও ক্যারিয়ার',
    titleEn: 'Academic &',
    titleBn: 'শিক্ষা ও',
    highlightWordEn: 'Professional Track',
    highlightWordBn: 'প্রশিক্ষণ',
    descEn: 'Authentic Islamic academic background, operational experience, and professional skill training.',
    descBn: 'প্রামাণ্য প্রাতিষ্ঠানিক শিক্ষা, অপারেশনাল অভিজ্ঞতা এবং প্রফেশনাল স্কিল ডেভেলপমেন্ট প্রশিক্ষণ।',
    academicList: [...academicList],
    academicListBn: [...academicListBn],
    trainingDataEn: { ...trainingDataEn },
    trainingDataBn: { ...trainingDataBn },
  },
  contact: {
    badgeEn: 'Contact & Collaborate',
    badgeBn: 'যোগাযোগ ও কাজ',
    titleEn: 'Ready to scale your brand with',
    titleBn: 'আপনার বিজনেসের বিক্রয় ও গ্রোথ বাড়াতে',
    highlightWordEn: 'high-ROI marketing?',
    highlightWordBn: 'যোগাযোগ করুন এখনই',
    descEn: 'Available for Meta ad campaigns, digital marketing strategy, Google Workspace operations, and high-impact media production.',
    descBn: 'মেটা অ্যাড ক্যাম্পেইন, ডিজিটাল মার্কেটিং স্ট্র্যাটেজি, গুগল ওয়ার্কস্পেস পরিচালনা এবং ভিডিও ও কনটেন্ট প্রোডাকশনের জন্য আমি প্রস্তুত।',
  },
};
